version: '3.8'
services:
  telegram-bot:
    image: telegram-bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-bot-container
    env_file:
      - .env_prod
    volumes:
      - ./.env_prod:/app/.env_prod
    command: python -m bot.main --env prod
    restart: unless-stopped
